# Generated by Django 2.2 on 2020-08-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catagory',
            field=models.CharField(default=2, max_length=120),
            preserve_default=False,
        ),
    ]
