# Generated by Django 2.2 on 2020-08-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(default='misc', max_length=120),
        ),
    ]
